ask_ustimov/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('', include('main_app.urls')),
]

main_app/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import hello_world
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$', views.QuestionsById.as_view(), name='index'),
    # url(r'^question/', TemplateView.as_view(template_name='question.html'), name='question'),
    url(r'^question/(?P<id>[0-9]+)/$', views.QuestionDetail.as_view(), name='question'),
    url(r'^tag/(?P<tag>[A-Za-z0-9]+)/$', views.QuestionsByTag.as_view(), name='tag'),
    url(r'^hot/$', views.QuestionsByLikes.as_view(), name='hot'),
    url(r'^ask/$', TemplateView.as_view(template_name='ask.html'), name='ask'),
    url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='login'),
    url(r'^signup/$', TemplateView.as_view(template_name='signup.html'), name='signup'),
    url(r'^hello_world/', hello_world),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class QuestionManager(models.Manager):
    def by_likes_gte(self, likes):
        return self.filter(likes__count__gte=likes).order_by('-likes__count')

    def by_tag(self, tag):
        return self.filter(tags=tag).order_by('-datetime')


class Tag(models.Model):
    text = models.CharField(max_length=32)


class Likes(models.Model):
    count = models.IntegerField(default=0)


class Question(models.Model):
    user = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag)
    likes = models.OneToOneField(Likes)
    title = models.CharField(max_length=128)
    text = models.CharField(max_length=4096)
    datetime = models.DateTimeField(default=now)
    objects = models.Manager()
    manager = QuestionManager()

    def get_absolute_url(self):
        return '/question/{0}/'.format(self.id)


class Answer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    likes = models.OneToOneField(Likes)
    text = models.CharField(max_length=2048)
    is_correct = models.BooleanField(default=False)
    datetime = models.DateTimeField(default=now)


class Profile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField()

main_app/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from . import models


@csrf_exempt
def hello_world(request):
    method = request.method
    if method == 'GET':
        params = dict(request.GET.lists())
    else:
        params = dict(request.POST.lists())
    response = '<!DOCTYPE html><head><meta charset="utf-8"></head><body>' \
               'Привет, мир!<br>Метод: {0}<br>Параметры: {1}</body></html>'.format(method, params)
    return HttpResponse(response)


class QuestionsById(ListView):
    model = models.Question
    template_name = 'index.html'
    paginate_by = 7
    context_object_name = 'questions'
    ordering = ['-datetime']


class QuestionsByTag(QuestionsById):
    def get_queryset(self):
        self.tag = get_object_or_404(models.Tag, text=self.kwargs['tag'])
        return models.Question.manager.by_tag(self.tag)

    def get_context_data(self, **kwargs):
        context = super(QuestionsByTag, self).get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class QuestionsByLikes(QuestionsById):
    def get_queryset(self):
        return models.Question.manager.by_likes_gte(0)

    def get_context_data(self, **kwargs):
        context = super(QuestionsByLikes, self).get_context_data(**kwargs)
        context['hot'] = True
        return context


class QuestionDetail(ListView):
    model = models.Answer
    template_name = 'question.html'
    paginate_by = 2
    context_object_name = 'answers'
    ordering = ['-likes__count']

    def get_queryset(self):
        self.question = get_object_or_404(models.Question, id=self.kwargs['id'])
        return models.Answer.objects.filter(question=self.question)

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['question'] = self.question
        return context

templates/ask.html
{% extends 'base.html' %}

{% block title %}New Question{% endblock %}

{% block content %}
<h1>New Question</h1>

<form class="form-horizontal">

    <div class="form-group">
        <label for="title" class="col-sm-1 control-label">Title</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="title" placeholder="Enter title here">
        </div>
    </div>

    <div class="form-group">
        <label for="text" class="col-sm-1 control-label">Text</label>
        <div class="col-sm-10">
            <textarea class="form-control textarea-no-resize" rows="15" id="text" placeholder="Enter text here"></textarea>
        </div>
    </div>

    <div class="form-group">
        <label for="tags" class="col-sm-1 control-label">Tags</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="tags" placeholder="Enter tags here">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="submit" class="btn btn-default">Ask!</button>
        </div>
    </div>

</form>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
        {% block title %}

        {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Custom -->
    <link href="{% static 'css/askustimov.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header col-lg-2 col-sm-2 col-md-2">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">AskUstimov</a>
                <div class="col-xs-2 col-xs-offset-3">
                    <div class="ask visible-xs">
                        <a href="{% url 'ask' %}"><div class="btn btn-success">ASK!</div></a>
                    </div>
                </div>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <div class="searchbar col-lg-5 col-sm-5 col-md-5">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
                <div class="col-lg-2 col-sm-2 col-md-2">
                    <div class="ask hidden-xs">
                        <a href="{% url 'ask' %}"><div class="btn btn-success">ASK!</div></a>
                    </div>
                </div>
                <ul class="nav navbar-nav col-lg-3 col-sm-3 col-md-3">
                    {% block menu %}
                        <li class="active"><a href="{% url 'login' %}">Log In</a></li>
                        <li><a href="{% url 'signup' %}">Register</a></li>
                    {% endblock %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="col-md-9">

            <div class="row col-md-12">
                <div class="btn-group mobile-menu visible-xs visible-sm" role="group">
                    <button type="button" class="btn btn-default" data-toggle="collapse" href="#collapseOne" aria-controls="collapseOne">Popular Tags</button>
                    <button type="button" class="btn btn-default" data-toggle="collapse" href="#collapseTwo" aria-controls="collapseTwo">Best Members</button>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <div id="collapseOne" class="collapse">
                            <h2>Popular Tags</h2>
                            perl <span class="red md-text">python</span> TechnoPark <span class="red lg-text">MySQL</span>
                            <span class="green md-text">django</span> Mail.Ru Voloshin <span class="orange md-text">Firefox</span>
                        </div>
                    </div>
                </div>
                <div class="collapse" id="collapseTwo">
                     <h2>Best Members</h2>
                    <ul class="best-members">
                        <li><a href="#">Mr. Freeman</a></li>
                        <li><a href="#">Dr. House</a></li>
                        <li><a href="#">Bander</a></li>
                        <li><a href="#">Queen Victoria</a></li>
                        <li><a href="#">A. Ustimov</a></li>
                    </ul>
                </div>
            </div>

            {% block content %}

            {% endblock %}
            {% if is_paginated %}
                <nav class="text-center">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li>
                                <a href="{% url 'index' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        {% for page in page_obj.paginator.page_range %}
                            {% if forloop.counter == 1 and page_obj.number|add:'-1' > 1 %}
                                {% if tag %}
                                    <li><a href="{% url 'tag' tag.text %}?page=1">1</a></li>
                                {% elif question %}
                                    <li><a href="{% url 'question' question.id %}?page=1">1</a></li>
                                {% elif hot %}
                                    <li><a href="{% url 'hot' %}?page=1">1</a></li>
                                {% else %}
                                     <li><a href="{% url 'index' %}?page=1">1</a></li>
                                {% endif %}
                                {% if page_obj.previous_page_number != 2 %}
                                    <li><a href="#">...</a></li>
                                {% endif %}
                            {% endif %}
                            {% if not page < page_obj.number|add:'-1' and not page > page_obj.number|add:'+1' %}
                                {% if page_obj.number == page %}
                                    <li class="active">
                                {% else %}
                                    <li>
                                {% endif %}
                                    {% if tag %}
                                        <a href="{% url 'tag' tag.text %}?page={{ page }}">{{ page }}</a>
                                    {% elif question %}
                                        <a href="{% url 'question' question.id %}?page={{ page }}">{{ page }}</a>
                                    {% elif hot %}
                                        <a href="{% url 'hot' %}?page={{ page }}">{{ page }}</a>
                                    {% else %}
                                        <a href="{% url 'index' %}?page={{ page }}">{{ page }}</a>
                                    {% endif %}
                                </li>
                            {% endif %}

                            {% if forloop.last and page_obj.number|add:'+1' < page_obj.paginator.page_range|length %}
                                {% if page_obj.next_page_number != page_obj.paginator.page_range|length|add:'-1' %}
                                    <li><a href="#">...</a></li>
                                {% endif %}
                                <li>
                                    {% if tag %}
                                        <a href="{% url 'tag' tag.text %}?page={{ page_obj.paginator.page_range|length }}">
                                            {{ page_obj.paginator.page_range|length }}
                                        </a>
                                    {% elif question %}
                                        <a href="{% url 'question' question.id %}?page={{ page_obj.paginator.page_range|length }}">
                                            {{ page_obj.paginator.page_range|length }}
                                        </a>
                                    {% elif hot %}
                                        <a href="{% url 'hot' %}?page={{ page_obj.paginator.page_range|length }}">
                                            {{ page_obj.paginator.page_range|length }}
                                        </a>
                                    {% else %}
                                        <a href="{% url 'index' %}?page={{ page_obj.paginator.page_range|length }}">
                                            {{ page_obj.paginator.page_range|length }}
                                        </a>
                                    {% endif %}
                                </li>
                            {% endif %}

                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li>
                                {% if tag %}
                                    <a href="{% url 'tag' tag.text %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                {% elif question %}
                                    <a href="{% url 'question' question.id %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                {% elif hot %}
                                    <a href="{% url 'hot' %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'index' %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                {% endif %}
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
        <div class="sidebar col-md-3 hidden-xs hidden-sm">
            <h2>Popular Tags</h2>
            perl <span class="red md-text">python</span> TechnoPark <span class="red lg-text">MySQL</span>
            <span class="green md-text">django</span> Mail.Ru Voloshin <span class="orange md-text">Firefox</span>
            <h2>Best Members</h2>
            <ul class="best-members">
                <li><a href="#">Mr. Freeman</a></li>
                <li><a href="#">Dr. House</a></li>
                <li><a href="#">Bander</a></li>
                <li><a href="#">Queen Victoria</a></li>
                <li><a href="#">A. Ustimov</a></li>
            </ul>
        </div>
    </div><!-- /.container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    {% if tag %}
        Tag: {{ tag.text }}
    {% elif hot %}
        Hot Questions
    {% else %}
        New Questions
    {% endif %}
{% endblock %}

{% block menu %}
<li>
    <div class="avatar"><img class="img-rounded" src="https://placehold.it/32x32">
        <span class="user">
            <div class="btn-group">
                Dr. Pepper
                <i class="fa fa-caret-down fa-lg dropdown-toggle options hidden-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                <ul class="dropdown-menu">
                    <li><a href="#">Settings</a></li>
                    <li><a href="#">Log Out</a></li>
                </ul>
            </div>
        </span>
    </div>
</li>
<li class="visible-xs"><a href="#">Settings</a></li>
<li class="visible-xs"><a href="#">Log Out</a></li>
{% endblock %}

{% block content %}
    {% if tag %}
        <h1>Tag: {{ tag.text }}</h1>
    {% elif hot %}
        <h1>Hot Questions</h1>
    {% else %}
        <h1>New Questions</h1>
    {% endif %}

    {% for question in questions %}
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-sm-2 text-center">
                    <img class="img-rounded" src="https://placehold.it/100x100">
                    <div class="rate">
                        <i role="button" class="fa fa-thumbs-o-down fa-lg thumbs-down"></i>
                        {{ question.likes.count }}
                        <i role="button" class="fa fa-thumbs-o-up fa-lg thumbs-up"></i>
                    </div>
                </div>
                <div class="col-sm-10">
                    <h3><a href="{{ question.get_absolute_url }}">{{ question.title }}</a></h3>
                    {{ question.text }}
                </div>
                <div class="panel-offset col-sm-2 col-xs-12">
                    <a href="{{ question.get_absolute_url }}">Answers ({{ question.answer_set.values|length }})</a>
                </div>
                <div class="panel-offset col-sm-8 col-xs-12">
                    Tags:
                    {% for tag in question.tags.values %}
                        <a href="{% url 'tag' tag.text %}">{{ tag.text }}</a>{% if not forloop.last %},{% endif %}
                    {% empty %}
                        there is no tags
                    {% endfor %}
                </div>
            </div>
        </div>
    {% empty %}
        There is no questions
    {% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Log In</h1>

<div class="alert alert-danger" role="alert">Sorry, wrong password!</div>

<form class="form-horizontal">

    <div class="form-group">
        <label for="login" class="col-sm-2 control-label">Login</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="login" placeholder="Enter your login here">
        </div>
    </div>

    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" id="password" placeholder="Password">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Log in!</button>
        </div>
    </div>

    <div class="col-sm-offset-2">
        <a href="{% url 'signup' %}">Create new account</a>
    </div>

</form>
{% endblock %}

templates/question.html
{% extends 'base.html' %}

{% block title %}{{ question.title }}{% endblock %}

{% block content %}
<h1></h1>
<div class="row">
    <div class="col-sm-3 col-md-3 text-center">
        <div class="question-img">
            <img class="img-rounded" src="https://placehold.it/120x120">
            <div class="rate text-center">
                <i role="button" class="fa fa-thumbs-o-down fa-lg thumbs-down"></i>
                {{ question.likes.count }}
                <i role="button" class="fa fa-thumbs-o-up fa-lg thumbs-up"></i>
            </div>
        </div>
    </div>
        <div class="col-sm-9 col-md-9">
        <h3>{{ question.title }}</h3>
        {{ question.text }}
    </div>
    <div class="panel-offset col-sm-9 col-md-9">
        Tags:
        {% for tag in question.tags.values %}
            <a href="{% url 'tag' tag.text %}">{{ tag.text }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
            there is no tags
        {% endfor %}
    </div>
</div>

<hr>

{% for answer in answers %}
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-sm-2 text-center">
                <img class="img-rounded" src="https://placehold.it/100x100">
                <div class="rate">
                    <i role="button" class="fa fa-thumbs-o-down fa-lg thumbs-down"></i>
                    {{ answer.likes.count }}
                    <i role="button" class="fa fa-thumbs-o-up fa-lg thumbs-up"></i>
                </div>
            </div>
            <div class="col-sm-10">
                {{ answer.text }}
            </div>
            {% if answer.is_correct %}
                <div class="panel-offset col-sm-2 col-xs-4">
                    <i class="fa fa-check fa-2x answer"></i>
                </div>
            {% else %}
                <div class="panel-offset col-sm-2 col-xs-4">
                    <a href="#"><div class="btn btn-default">Correct</div></a>
                </div>
            {% endif %}
        </div>
    </div>
{% empty %}
    There is no answers
{% endfor %}

<hr>

<div class="col-sm-12">
    <form class="form-horizontal">
        <div class="form-group">
            <textarea class="form-control textarea-no-resize" rows="10" id="text" placeholder="Enter your answer here"></textarea>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-default">Answer</button>
        </div>
    </form>
</div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
<h1>Registration</h1>

<div class="alert alert-danger" role="alert">Sorry, this email address already registered!</div>

<form class="form-horizontal">

    <div class="form-group">
        <label for="login" class="col-sm-3 control-label">Login</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="login" placeholder="Enter your login here">
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Email</label>
        <div class="col-sm-6">
            <input type="email" class="form-control" id="email" placeholder="Enter your email here">
        </div>
    </div>

    <div class="form-group">
        <label for="nickname" class="col-sm-3 control-label">Nickname</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="nickname" placeholder="Enter your nickname here">
        </div>
    </div>

    <div class="form-group">
        <label for="password" class="col-sm-3 control-label">Password</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" id="password" placeholder="Password">
        </div>
    </div>

    <div class="form-group">
        <label for="password2" class="col-sm-3 control-label">Repeat password</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" id="password2" placeholder="Repeat password">
        </div>
    </div>

    <div class="form-group">
        <label for="image" class="col-sm-3 control-label">Upload avatar</label>
        <div class="col-sm-6">
            <input type="file" id="image">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
            <button type="submit" class="btn btn-default">Register!</button>
        </div>
    </div>

</form>
{% endblock %}